// app/Home/page.tsx
	// Auto-generated by Theme Editor - Do not edit manually

	import PageRenderer from '@/components/PageRenderer';

	export default function GeneratedPage() {
		const pageData = {
    "isHome": true,
    "metaDescription": "Discover premium homes, luxury apartments, and land for sale in Lagos Nigeria. Buy, rent, or sell properties fast with Nigeria's trusted real estate agency. Expert agents, verified listings in Lekki, Ikoyi, Victoria Island \u0026 more.",
    "sections": [
      {
        "props": {},
        "type": "HeaderVar1"
      },
      {
        "props": {
          "location": "Lagos, Nigeria",
          "price": "450000",
          "pro_info": {},
          "title": "Luxury Villa"
        },
        "type": "PropCardVar1"
      },
      {
        "props": {},
        "type": "FooterVar1"
      }
    ],
    "slug": "/",
    "title": "Lagos Realty: Home Page",
    "uid": "home-page-001"
  };

		return <PageRenderer data={pageData} />;
	}

	// Optional: Metadata for SEO
	export async function generateMetadata() {
		return {
			title: "Lagos Realty: Home Page",
			description: "",
		};
	}